name: Deploy Dist folder
# on: [push,workflow_dispatch]
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              run: |
                  echo "Cloning repo"
                  echo "${{toJson(github)}}"
                  git clone https://github.com/${{github.repository}}.git myfiles
                  cd myfiles && ls