name: Deploy Dist folder
# on: [push,workflow_dispatch]
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              run: |
                  echo "Cloning repo"
                  git clone https://github.com/tauqirnasir/react-cidcd-demo-gitactions.git myfiles
                  cd myfiles && ls