name: Greet User
# on: push
on: workflow_dispatch
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: greet user
              run: echo " Hellow World!"
            - name: By user
              run: echo "Bye Bye!!"